language: node_js
node_js:
  - node
script: script/cibuild
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  on
    branch: master
